name: 'Stale Package'
description: 'GitHub Action to find a Python package''s publication date and fail if stale'
inputs:
  package:
    description: 'Package name'
    required: true
  best-before:
    description: 'Fail if the package is older than this date (or number of days)'
    required: false
    default: '365'
  index:
    description: 'Index to extract publication date from'
    required: false
    default: 'pypi'
outputs:
  version:
    description: 'Version of installed package'
  date-published:
    description: 'Date installed package was published'
runs:
  using: 'node16'
  main: 'dist/index.js'
